module.exports = {
  "mealdb-52938": {
    en: {
      subtitle: "Turmeric in the pastry, allspice in the beef",
      description: "The pastry is yellow from turmeric and short from shortening; the filling is beef stewed down with allspice and thyme until the liquid has gone. Both halves must be cold before you assemble.",
      instructions: [
        "First, the pastry dough.",
        "To a large bowl, add the flour, 1 teaspoon salt and turmeric and mix thoroughly.",
        "Rub the shortening into the flour until there are small pieces of shortening completely coated in flour.",
        "Pour in 1/2 cup of the ice water and mix with your hands to bring the dough together. Keep adding ice water 2 to 3 tablespoons at a time until it forms a dough.",
        "At this point you can cut the dough into 2 large pieces, wrap them in plastic and refrigerate 30 minutes before using.",
        "Or cut it into 10 to 12 equal pieces, lay them on a platter or baking sheet, cover securely with plastic wrap and chill 30 minutes while you make the filling. Now the filling.",
        "Put the ground beef in a large bowl. Sprinkle in the allspice and black pepper. Mix together and set aside.",
        "Heat the oil in a skillet until hot.",
        "Add the onions and sauté until translucent. Add the hot pepper, garlic and thyme and sauté another minute. Add 1/4 teaspoon salt.",
        "Add the seasoned beef and toss to mix, breaking up the clumps, and cook until the meat is no longer pink.",
        "Add the ketchup and more salt to taste.",
        "Pour in 2 cups of water and stir. Bring it to the boil, then lower the heat and simmer until most of the liquid has gone and what is left has reduced to a thick sauce.",
        "Fold in the green onions. Take it off the heat and let it cool completely — warm filling will melt the pastry as you fold it. Now assemble.",
        "Beat the egg and water together to make an egg wash and set it aside.",
        "There are two ways to work the dough from here.",
        "First method: flour the work surface and rolling pin. If you cut it into 2 large pieces, take one and roll it into a very large circle. Take a bowl with a wide rim, about 5 inches, and cut out three circles.",
        "Put about 3 heaping tablespoons of filling onto 1/2 of each circle. Dip a finger in water and moisten the edges. Fold the other half over and press to seal.",
        "Crimp the edges with a fork and trim off any excess so they look neat and even. Lay them on a parchment-lined baking sheet and carry on until all the dough is rolled and all the patties filled.",
        "Second method: if you cut the dough into individual pieces, work one at a time. Roll it out on a floured surface into a 5-inch circle or a little bigger. Don't worry if the edges aren't perfect.",
        "Put 3 heaping tablespoons of filling on one side of the circle. Dip a finger in water and moisten the edges. Fold the other half over and press to seal.",
        "Crimp the edges with a fork and trim off any excess. Lay them on a parchment-lined baking sheet and carry on until all the dough is rolled and all the patties filled.",
        "Now bake and serve.",
        "Once they are formed, put the pans in the refrigerator while you heat the oven to 350 F.",
        "Brush the patties with the egg wash just before the pans go in.",
        "Bake 30 minutes, or until golden brown. Cool on wire racks and serve warm."
      ]
    },
    nl: {
      subtitle: "Kurkuma in het deeg, piment in het gehakt",
      description: "Het deeg is geel van de kurkuma en bros van het bakvet; de vulling is rundvlees gestoofd met piment en tijm tot het vocht weg is. Beide helften moeten koud zijn voor je ze samenbrengt.",
      instructions: [
        "Eerst het deeg.",
        "Doe de bloem, 1 theelepel zout en de kurkuma in een grote kom en meng grondig.",
        "Wrijf het bakvet door de bloem tot er kleine stukjes bakvet zijn die volledig met bloem bedekt zijn.",
        "Giet er 1/2 kopje ijswater bij en meng met je handen tot het deeg samenkomt. Blijf ijswater toevoegen, 2 tot 3 eetlepels per keer, tot het een deeg vormt.",
        "Op dit punt kan je het deeg in 2 grote stukken snijden, ze in plastic wikkelen en 30 minuten in de koelkast leggen voor gebruik.",
        "Of snijd het in 10 tot 12 gelijke stukken, leg ze op een schaal of bakplaat, dek goed af met folie en zet ze 30 minuten koud terwijl je de vulling maakt. Nu de vulling.",
        "Doe het rundergehakt in een grote kom. Strooi er de piment en de zwarte peper over. Meng door elkaar en zet opzij.",
        "Verhit de olie in een pan tot ze heet is.",
        "Voeg de uien toe en fruit ze tot ze glazig zijn. Voeg de hete peper, de knoflook en de tijm toe en bak nog een minuut. Voeg 1/4 theelepel zout toe.",
        "Voeg het gekruide gehakt toe en schep om, terwijl je de klonters losbreekt, en bak tot het vlees niet meer rood is.",
        "Voeg de ketchup en naar smaak meer zout toe.",
        "Giet er 2 kopjes water bij en roer. Breng aan de kook, zet dan lager en laat sudderen tot het meeste vocht weg is en wat overblijft tot een dikke saus is ingekookt.",
        "Spatel de lente-ui erdoor. Haal van het vuur en laat volledig afkoelen — warme vulling smelt het deeg terwijl je vouwt. Nu opbouwen.",
        "Klop het ei en het water samen tot een eierwas en zet die opzij.",
        "Vanaf hier kan je het deeg op twee manieren aanpakken.",
        "Eerste manier: bebloem het werkblad en de deegrol. Heb je het in 2 grote stukken gesneden, neem er dan één en rol het uit tot een heel grote cirkel. Neem een kom met een brede rand, ongeveer 5 inch, en steek er drie cirkels mee uit.",
        "Doe ongeveer 3 volle eetlepels vulling op 1/2 van elke cirkel. Doop een vinger in water en bevochtig de randen. Vouw de andere helft eroverheen en druk aan om te sluiten.",
        "Kartel de randen met een vork en snijd het teveel weg zodat ze er netjes en gelijk uitzien. Leg ze op een met bakpapier beklede bakplaat en ga door tot al het deeg uitgerold en alle pasteitjes gevuld zijn.",
        "Tweede manier: heb je het deeg in aparte stukken gesneden, werk dan één stuk per keer. Rol het op een bebloemd werkblad uit tot een cirkel van 5 inch of iets groter. Geen zorgen als de randen niet perfect zijn.",
        "Doe 3 volle eetlepels vulling op één kant van de cirkel. Doop een vinger in water en bevochtig de randen. Vouw de andere helft eroverheen en druk aan om te sluiten.",
        "Kartel de randen met een vork en snijd het teveel weg. Leg ze op een met bakpapier beklede bakplaat en ga door tot al het deeg uitgerold en alle pasteitjes gevuld zijn.",
        "Nu bakken en opdienen.",
        "Zet de platen, zodra de pasteitjes gevormd zijn, in de koelkast terwijl je de oven op 350 F verwarmt.",
        "Bestrijk de pasteitjes met de eierwas net voor de platen erin gaan.",
        "Bak 30 minuten, of tot ze goudbruin zijn. Laat afkoelen op roosters en dien lauw op."
      ]
    },
    fr: {
      subtitle: "Du curcuma dans la pâte, du piment de la Jamaïque dans le bœuf",
      description: "La pâte est jaune de curcuma et sablée par le shortening ; la farce est du bœuf mijoté au piment de la Jamaïque et au thym jusqu'à ce que le liquide ait disparu. Les deux moitiés doivent être froides au montage.",
      instructions: [
        "D'abord, la pâte.",
        "Dans un grand bol, mets la farine, 1 cuillère à café de sel et le curcuma et mélange soigneusement.",
        "Sable le shortening dans la farine jusqu'à obtenir de petits morceaux entièrement enrobés de farine.",
        "Verse 1/2 tasse d'eau glacée et mélange à la main pour rassembler la pâte. Continue d'ajouter de l'eau glacée, 2 à 3 cuillères à soupe à la fois, jusqu'à obtenir une pâte.",
        "À ce stade, tu peux couper la pâte en 2 gros morceaux, les emballer dans du film et réfrigérer 30 minutes avant usage.",
        "Ou coupe-la en 10 à 12 morceaux égaux, pose-les sur un plat ou une plaque, couvre bien de film et réfrigère 30 minutes pendant que tu prépares la farce. La farce maintenant.",
        "Mets le bœuf haché dans un grand bol. Saupoudre le piment de la Jamaïque et le poivre noir. Mélange et réserve.",
        "Chauffe l'huile dans une poêle jusqu'à ce qu'elle soit chaude.",
        "Ajoute les oignons et fais-les revenir jusqu'à ce qu'ils soient translucides. Ajoute le piment fort, l'ail et le thym et poursuis une minute. Ajoute 1/4 de cuillère à café de sel.",
        "Ajoute le bœuf assaisonné et mélange en défaisant les grumeaux, et cuis jusqu'à ce que la viande ne soit plus rosée.",
        "Ajoute le ketchup et du sel selon ton goût.",
        "Verse 2 tasses d'eau et remue. Porte à ébullition, puis baisse le feu et laisse mijoter jusqu'à ce que le plus gros du liquide se soit évaporé et que le reste soit réduit en sauce épaisse.",
        "Incorpore les oignons verts. Retire du feu et laisse refroidir complètement — une farce tiède fera fondre la pâte au pliage. Le montage maintenant.",
        "Bats l'œuf et l'eau ensemble pour la dorure et réserve.",
        "À partir d'ici, deux façons de travailler la pâte.",
        "Première méthode : farine le plan de travail et le rouleau. Si tu l'as coupée en 2 gros morceaux, prends-en un et étale-le en un très grand cercle. Prends un bol à bord large, environ 5 pouces, et découpe trois disques.",
        "Dépose environ 3 grosses cuillères à soupe de farce sur 1/2 de chaque disque. Trempe un doigt dans l'eau et humidifie les bords. Rabats l'autre moitié et presse pour souder.",
        "Cannelle les bords à la fourchette et recoupe l'excédent pour que ce soit net et régulier. Pose-les sur une plaque chemisée et continue jusqu'à ce que toute la pâte soit étalée et tous les chaussons garnis.",
        "Deuxième méthode : si tu as prédécoupé la pâte en morceaux, travaille un morceau à la fois. Étale-le sur un plan fariné en un disque de 5 pouces ou un peu plus. Peu importe si les bords ne sont pas parfaits.",
        "Dépose 3 grosses cuillères à soupe de farce sur une moitié du disque. Trempe un doigt dans l'eau et humidifie les bords. Rabats l'autre moitié et presse pour souder.",
        "Cannelle les bords à la fourchette et recoupe l'excédent. Pose-les sur une plaque chemisée et continue jusqu'à ce que toute la pâte soit étalée et tous les chaussons garnis.",
        "La cuisson et le service maintenant.",
        "Une fois les chaussons formés, mets les plaques au réfrigérateur pendant que tu chauffes le four à 350 F.",
        "Badigeonne les chaussons de dorure juste avant d'enfourner.",
        "Cuis 30 minutes, ou jusqu'à ce qu'ils soient bien dorés. Laisse refroidir sur des grilles et sers tiède."
      ]
    }
  },

  "mealdb-53449": {
    dropSteps: [2, 5, 6, 14, 16, 17, 18, 20, 23],
    en: {
      subtitle: "Cabbage rolls steamed on a bed of their own trimmings",
      description: "Azerbaijani stuffed cabbage: lamb, rice and chickpeas rolled raw into blanched leaves, then steamed over the discarded leaves and stalks. They have to be weighted or they unwrap.",
      instructions: [
        "First boil the rice for eight minutes. Meanwhile, peel and finely chop the onion, then chop the herbs.",
        "Roughly chop or lightly mash the chickpeas so they work into the filling rather than sit in it as whole beans.",
        "Now mince the lamb — a small food processor does this easily. Mince the lamb fat along with it; it looks unpromising and it is exactly what makes the filling juicy. Lamb fat does not simply melt away in the steam the way you might hope, so mincing it finely is what gets it evenly through the filling.",
        "Get your hands into the raw meat and mix in the onion, spices, chickpeas, rice, chopped herbs and fat. Add salt and pepper, and err on the generous side — this filling takes more seasoning than you would think.",
        "Mix well with your hands until the stuffing is evenly combined all the way through.",
        "Fill the biggest saucepan you own with salted water and bring it to the boil over high heat. Pull the outer leaves off the cabbage and keep them, then drop the rest of it in whole. Let it boil three or four minutes, turning it if the water doesn't quite cover it.",
        "The blanching is the point here. A supermarket cabbage comes as a tight round ball, and because the leaves are crisp they snap and crack when you try to pull them off raw. A few minutes in boiling water and they come away whole, which is the only way this dish works.",
        "Carefully lift the cabbage out, keeping the water boiling, and let it cool a minute or two so you don't burn your fingers. Pull the leaves off, cutting them at the base if you have to. Try to get them off in one piece.",
        "If the inner leaves are still crisp, put the cabbage back into the boiling water for another three or four minutes. Repeat until all the usable leaves are free.",
        "Put the leaves on a cutting board and cut out the tough stalks — keep those too. Cut the largest leaves in half.",
        "Put a heaping tablespoon of filling in the middle of each leaf in a short cylinder. Fold the ends over the filling, then roll it up tightly, like a very small burrito.",
        "Put all the discarded cabbage leaves and stalks in the bottom of a stockpot. It seems strange, but you are building a steamer: the scraps are the base and the dolma sit on them. Place the dolma carefully on that bed.",
        "Add water to the stockpot up to about the top of the discarded leaves. Don't cover the dolma themselves.",
        "Now improvise a weight. The dolma have to be held down or they unwrap as they cook. A metal pie pan with something heavy on it works; so does a heatproof dessert plate weighted down.",
        "Bring the water to the boil, then simmer 25 minutes. You may have to go by ear to tell whether it is boiling, since the weight hides everything.",
        "Meanwhile, make a simple tomato sauce from the tomato paste and water and heat it a few minutes over a medium flame. Once the dolma have had their 25 minutes, pour the sauce over them and cook another five minutes."
      ]
    },
    nl: {
      subtitle: "Koolrolletjes gestoomd op een bed van hun eigen afval",
      description: "Azerbeidzjaanse gevulde kool: lam, rijst en kikkererwten rauw in geblancheerde bladeren gerold en dan gestoomd boven de weggesneden bladeren en stronken. Ze moeten verzwaard worden, anders rollen ze open.",
      instructions: [
        "Kook eerst de rijst acht minuten. Pel en snipper ondertussen de ui, en hak dan de kruiden.",
        "Hak of prak de kikkererwten grof zodat ze in de vulling opgaan in plaats van er als hele bonen in te liggen.",
        "Maal nu het lamsvlees — een kleine keukenmachine doet dat zo. Maal het lamsvet er meteen bij; het ziet er weinig aanlokkelijk uit en het is net wat de vulling sappig maakt.",
        "Steek je handen in het rauwe vlees en meng er de ui, de specerijen, de kikkererwten, de rijst, de gehakte kruiden en het vet door. Voeg zout en peper toe, en wees eerder royaal — deze vulling verdraagt meer kruiding dan je zou denken.",
        "Meng goed met je handen tot de vulling er helemaal door gelijkmatig is.",
        "Vul de grootste pan die je hebt met gezouten water en breng het op hoog vuur aan de kook. Trek de buitenste bladeren van de kool en hou ze bij, en laat de rest er in zijn geheel in zakken. Laat drie of vier minuten koken, en draai de kool als het water hem niet helemaal bedekt.",
        "Om het blancheren is het hier te doen. Een supermarktkool is een strakke bal van knapperige bladeren die breken en scheuren als je ze rauw lostrekt. Een paar minuten in kokend water en ze komen er heel af.",
        "Til de kool er voorzichtig uit terwijl je het water aan de kook houdt, en laat hem een minuut of twee afkoelen zodat je je vingers niet brandt. Trek de bladeren eraf en snijd ze aan de voet los als het moet. Probeer ze in één stuk te houden.",
        "Zijn de binnenste bladeren nog knapperig, doe de kool dan nog drie of vier minuten terug in het kokende water. Herhaal tot alle bruikbare bladeren los zijn.",
        "Leg de bladeren op een snijplank en snijd de harde nerven eruit — hou die ook bij. Snijd de grootste bladeren doormidden.",
        "Leg een volle eetlepel vulling in het midden van elk blad, in een korte rol. Vouw de uiteinden over de vulling en rol dan strak op, als een heel kleine burrito.",
        "Leg alle weggesneden koolbladeren en nerven op de bodem van een soeppan. Het lijkt vreemd, maar je bouwt een stoommandje: de restjes zijn de bodem en de dolma liggen erop. Leg de dolma voorzichtig op dat bed.",
        "Giet water in de pan tot ongeveer de bovenkant van de weggesneden bladeren. Zet de dolma zelf niet onder.",
        "Improviseer nu een gewicht. De dolma moeten neergedrukt worden of ze rollen open tijdens het garen. Een metalen taartvorm met iets zwaars erop werkt, en een hittebestendig dessertbordje met een gewicht erop ook.",
        "Breng het water aan de kook en laat dan 25 minuten sudderen. Misschien moet je op je gehoor afgaan om te weten of het kookt, want het gewicht verbergt alles.",
        "Maak ondertussen een eenvoudige tomatensaus van de tomatenpuree en water en verwarm ze een paar minuten op middelhoog vuur. Als de dolma hun 25 minuten gehad hebben, giet je de saus eroverheen en gaar je nog vijf minuten."
      ]
    },
    fr: {
      subtitle: "Des roulés de chou cuits à la vapeur sur un lit de leurs propres chutes",
      description: "Un chou farci azerbaïdjanais : agneau, riz et pois chiches roulés crus dans des feuilles blanchies, puis cuits à la vapeur au-dessus des feuilles et des côtes écartées. Il faut les lester, sinon ils se déroulent.",
      instructions: [
        "Fais d'abord cuire le riz huit minutes. Pendant ce temps, épluche et hache finement l'oignon, puis hache les herbes.",
        "Hache grossièrement ou écrase légèrement les pois chiches pour qu'ils s'intègrent à la farce au lieu d'y rester en billes entières.",
        "Hache maintenant l'agneau — un petit robot le fait sans peine. Hache la graisse d'agneau avec ; ça n'a l'air de rien et c'est exactement ce qui rend la farce juteuse. La graisse d'agneau ne fond pas simplement à la vapeur comme on pourrait l'espérer, donc la hacher finement est ce qui la répartit dans la farce.",
        "Plonge les mains dans la viande crue et mélange l'oignon, les épices, les pois chiches, le riz, les herbes hachées et la graisse. Ajoute sel et poivre, et sois plutôt généreux — cette farce en demande plus qu'on ne croit.",
        "Mélange bien à la main jusqu'à ce que la farce soit parfaitement homogène.",
        "Remplis la plus grande casserole que tu as d'eau salée et porte à ébullition à feu vif. Détache les feuilles extérieures du chou et garde-les, puis plonge le reste entier. Laisse bouillir trois ou quatre minutes, en le retournant si l'eau ne le couvre pas tout à fait.",
        "Le blanchiment est ici l'essentiel. Un chou de supermarché est une boule serrée de feuilles croquantes qui cassent et se déchirent si on les arrache crues. Quelques minutes dans l'eau bouillante et elles se détachent entières.",
        "Sors le chou délicatement en gardant l'eau bouillante, et laisse-le tiédir une minute ou deux pour ne pas te brûler les doigts. Détache les feuilles, en les coupant à la base si nécessaire. Essaie de les avoir d'une pièce.",
        "Si les feuilles intérieures sont encore croquantes, remets le chou dans l'eau bouillante trois ou quatre minutes de plus. Répète jusqu'à ce que toutes les feuilles utilisables soient libres.",
        "Pose les feuilles sur une planche et découpe les côtes dures — garde-les aussi. Coupe les plus grandes feuilles en deux.",
        "Dépose une grosse cuillère à soupe de farce au milieu de chaque feuille, en petit boudin. Rabats les extrémités sur la farce, puis roule serré, comme un tout petit burrito.",
        "Mets toutes les feuilles et côtes écartées au fond d'une marmite. Cela paraît étrange, mais tu construis un cuit-vapeur : les chutes font le fond et les dolmas reposent dessus. Dépose les dolmas avec soin sur ce lit.",
        "Ajoute de l'eau dans la marmite jusqu'au sommet des feuilles écartées environ. Ne recouvre pas les dolmas eux-mêmes.",
        "Improvise maintenant un poids. Les dolmas doivent être maintenus ou ils se déroulent à la cuisson. Un moule à tarte en métal avec quelque chose de lourd dessus convient ; une assiette à dessert résistante lestée aussi.",
        "Porte l'eau à ébullition, puis laisse frémir 25 minutes. Il te faudra peut-être te fier à l'oreille pour savoir si ça bout, puisque le poids cache tout.",
        "Pendant ce temps, fais une simple sauce tomate avec le concentré et de l'eau et chauffe-la quelques minutes à feu moyen. Une fois les 25 minutes des dolmas écoulées, verse la sauce dessus et cuis encore cinq minutes."
      ]
    }
  },

  "mealdb-53463": {
    en: {
      subtitle: "Boulets à la liégeoise, sweet-sour with sirop de Liège",
      description: "Liège's own meatball, braised in a sauce of caramelised onion, vinegar and the dark apple-and-pear syrup the city is named for. Sweet against sour is the whole balance; taste and tilt it your way.",
      instructions: [
        "First, the meatballs.",
        "Mix the minced meat with the onion, garlic, egg, breadcrumbs, mustard, parsley, salt and pepper.",
        "Shape it into meatballs. Liège restaurants traditionally serve one or two very large ones, depending on the appetite in front of them.",
        "For a weeknight, smaller is easier — they brown faster and cook through sooner. Now brown them.",
        "Heat butter or oil in a large pan.",
        "Brown the meatballs on all sides until they have a good crust.",
        "Take them out of the pan and set them aside. Now the sauce.",
        "In the same pan, melt 1 tbsp butter.",
        "Add the sliced onions and cook until soft and lightly caramelised.",
        "Sprinkle in the brown sugar and let it melt into the onions.",
        "Now deglaze and add the stock.",
        "Add the vinegar and scrape up all the browned bits from the bottom of the pan — that is where the flavour is.",
        "Stir in the mustard and Liège syrup.",
        "Pour in the beef stock, and the beer if you are using it. Add the bay leaf.",
        "Stir until the syrup has dissolved and the sauce looks glossy. Now simmer and adjust.",
        "Return the meatballs to the pan.",
        "Cover and simmer gently 25–30 minutes — less if your meatballs are small, longer for traditional large boulets. Stir now and then and let the sauce thicken on its own.",
        "Taste and adjust: more syrup for sweetness, more vinegar for tang, more mustard for depth. It should end up sweet-sour, rich and velvety.",
        "Serve with fries or mashed potatoes."
      ]
    },
    nl: {
      subtitle: "Boulets à la liégeoise, zoetzuur met siroop van Luik",
      description: "De gehaktbal van Luik, gesmoord in een saus van gekarameliseerde ui, azijn en de donkere appel-en-perensiroop waar de stad om bekend staat. Zoet tegen zuur is de hele balans; proef en stuur bij naar jouw hand.",
      instructions: [
        "Eerst de balletjes.",
        "Meng het gehakt met de ui, de knoflook, het ei, het paneermeel, de mosterd, de peterselie, het zout en de peper.",
        "Vorm er ballen van. Luikse restaurants dienen traditioneel één of twee heel grote op, naargelang de eetlust die voor hen zit.",
        "Voor doordeweeks is kleiner makkelijker — ze kleuren sneller en zijn eerder gaar. Nu bruinen.",
        "Verhit boter of olie in een grote pan.",
        "Braad de balletjes rondom bruin tot ze een mooie korst hebben.",
        "Haal ze uit de pan en zet ze opzij. Nu de saus.",
        "Smelt 1 el boter in dezelfde pan.",
        "Voeg de gesneden uien toe en bak ze tot ze zacht en lichtjes gekarameliseerd zijn.",
        "Strooi de bruine suiker erover en laat ze in de uien smelten.",
        "Nu deglaceren en de bouillon erbij.",
        "Voeg de azijn toe en schraap alle aanbaksels van de bodem los — daar zit de smaak.",
        "Roer de mosterd en de Luikse siroop erdoor.",
        "Giet de runderbouillon erbij, en het bier als je dat gebruikt. Voeg het laurierblad toe.",
        "Roer tot de siroop opgelost is en de saus glanst. Nu sudderen en bijsturen.",
        "Doe de balletjes terug in de pan.",
        "Dek af en laat 25–30 minuten zachtjes sudderen — korter als je balletjes klein zijn, langer voor traditionele grote boulets. Roer af en toe en laat de saus vanzelf indikken.",
        "Proef en stuur bij: meer siroop voor zoet, meer azijn voor zuur, meer mosterd voor diepte. Ze hoort zoetzuur, rijk en fluweelzacht te eindigen.",
        "Dien op met frieten of aardappelpuree."
      ]
    },
    fr: {
      subtitle: "Des boulets à la liégeoise, aigres-doux au sirop de Liège",
      description: "La boulette de Liège, mijotée dans une sauce d'oignons caramélisés, de vinaigre et du sirop sombre de pommes et de poires qui a fait la réputation de la ville. Le sucré contre l'acide fait tout l'équilibre ; goûte et penche à ta façon.",
      instructions: [
        "D'abord, les boulettes.",
        "Mélange la viande hachée avec l'oignon, l'ail, l'œuf, la chapelure, la moutarde, le persil, le sel et le poivre.",
        "Façonne des boulettes. Les restaurants liégeois en servent traditionnellement une ou deux très grosses, selon l'appétit en face.",
        "En semaine, plus petites c'est plus commode — elles dorent plus vite et cuisent à cœur plus tôt. Fais-les dorer maintenant.",
        "Chauffe du beurre ou de l'huile dans une grande poêle.",
        "Fais dorer les boulettes sur toutes les faces jusqu'à obtenir une belle croûte.",
        "Sors-les de la poêle et réserve. La sauce maintenant.",
        "Dans la même poêle, fais fondre 1 c. à soupe de beurre.",
        "Ajoute les oignons émincés et cuis jusqu'à ce qu'ils soient tendres et légèrement caramélisés.",
        "Saupoudre la cassonade et laisse-la fondre dans les oignons.",
        "Déglace maintenant et ajoute le bouillon.",
        "Ajoute le vinaigre et gratte tous les sucs du fond de la poêle — c'est là qu'est le goût.",
        "Incorpore la moutarde et le sirop de Liège.",
        "Verse le bouillon de bœuf, et la bière si tu en mets. Ajoute la feuille de laurier.",
        "Remue jusqu'à ce que le sirop soit dissous et que la sauce brille. Mijote et ajuste maintenant.",
        "Remets les boulettes dans la poêle.",
        "Couvre et laisse mijoter doucement 25 à 30 minutes — moins si tes boulettes sont petites, plus pour de vrais gros boulets. Remue de temps en temps et laisse la sauce épaissir toute seule.",
        "Goûte et ajuste : plus de sirop pour le sucré, plus de vinaigre pour l'acidité, plus de moutarde pour la profondeur. Elle doit finir aigre-douce, riche et veloutée.",
        "Sers avec des frites ou de la purée."
      ]
    }
  },

  "mealdb-52810": {
    en: {
      subtitle: "Two hours in a low oven, finished with gremolata",
      description: "Veal shanks braised until the meat gives up the bone and the marrow goes soft inside it. Half the gremolata goes on for the last fifteen minutes, half at the table — the hot sauce sets it off.",
      instructions: [
        "Heat the oven to 300 degrees.",
        "Dredging the shanks: pour the flour into a shallow dish — a pie plate is ideal. Season the veal shanks all over with salt and pepper. One at a time, roll each shank in the flour, then shake and pat it to knock off the excess. Throw the leftover flour away.",
        "Browning the shanks: put the oil and 1 tablespoon of the butter in a wide Dutch oven or heavy braising pot, 6 to 7 quart, and heat it over medium-high heat.",
        "When the butter has melted and the oil is shimmering, lower the shanks in flat side down. If they won't fit without touching, do it in batches. Brown them, turning once with tongs, until both flat sides are well caramelized, about 5 minutes a side.",
        "If the butter and oil start to burn, lower the heat a little. Move the shanks to a large platter or tray and set them aside.",
        "The aromatics: pour off and discard the fat. Wipe out any burnt bits with a damp paper towel, being careful to leave the good caramelized ones behind. Add the remaining 2 tablespoons butter and melt it over medium heat.",
        "When the butter has stopped foaming, add the onion, carrot, celery and fennel. Season with salt and pepper, stir, and cook until the vegetables begin to soften but do not brown, about 6 minutes. Stir in the garlic, orange zest, marjoram and bay leaf and stew another minute or two.",
        "The braising liquid: add the wine, turn the heat to high and bring it to the boil. Boil, stirring occasionally, until the wine has reduced by about half, 5 minutes. Add the stock and tomatoes with their juice and boil again to reduce the liquid to about 1 cup in total, about 10 minutes.",
        "The braise: set the shanks in the pot with the exposed bone facing up, and pour over any juices that collected while they sat. Cover with parchment paper, pressing it down so it nearly touches the veal and the edges hang an inch over the sides of the pot.",
        "Cover tightly with the lid and slide it into the lower part of the oven to braise at a gentle simmer. Check after the first 15 minutes, and if it is simmering too hard, drop the oven by 10 or 15 degrees.",
        "Carry on braising, turning the shanks and spooning pan juices over them after the first 40 minutes, until the meat is completely tender and pulling away from the bone, about 2 hours.",
        "The gremolata: while the shanks braise, stir the garlic, parsley and lemon zest together in a small bowl. Cover with plastic wrap and keep it somewhere cool, or the fridge if your kitchen is warm.",
        "The finish: when the veal is fork-tender and falling off the bone, take the lid off and scatter over half the gremolata. Put it back in the oven uncovered for another 15 minutes to caramelize.",
        "With a slotted spatula or spoon, lift the shanks out of the braising liquid, doing your best to keep them whole. They will be very tender and ready to fall apart, and the marrow will be wobbly inside the bones, so take it slowly.",
        "If they do break, it doesn't matter — the flavour is exactly the same. Arrange them on a serving platter without stacking and cover with foil to keep warm.",
        "Finishing the sauce: set the pot back on the stove and look at the sauce. If there is a visible layer of fat on the surface, skim it off with a large spoon. Taste it for concentration.",
        "If it tastes weak or flat, bring it to the boil over high heat and reduce it for 5 to 10 minutes to intensify. Taste again for salt and pepper. If it wants more zip, stir in a teaspoon or two of the remaining gremolata.",
        "Portioning: if the shanks are a reasonable size, serve one each. If they are enormous, or the appetites are modest, pull the larger ones apart at their natural seams and serve smaller amounts. Give the marrow bones to whoever prizes them most.",
        "Serving: arrange the shanks on warm plates with the risotto, if you are serving it. Just before you carry them to the table, scatter over the rest of the gremolata and spoon a generous amount of sauce over — the hot liquid releases the garlic and lemon, and that is what people smell as the plate arrives."
      ]
    },
    nl: {
      subtitle: "Twee uur in een lage oven, afgewerkt met gremolata",
      description: "Kalfsschenkel gesmoord tot het vlees het bot loslaat en het merg erin zacht wordt. De helft van de gremolata gaat erop voor de laatste kwartier, de helft aan tafel — de hete saus doet ze opengaan.",
      instructions: [
        "Verwarm de oven op 300 graden.",
        "De schenkels bebloemen: giet de bloem in een ondiepe schaal — een taartvorm is ideaal. Kruid de kalfsschenkels rondom met zout en peper. Rol ze één voor één door de bloem, en schud en klop het teveel eraf. Gooi de resterende bloem weg.",
        "De schenkels bruinen: doe de olie en 1 eetlepel van de boter in een brede braadpan of zware stoofpot van 6 tot 7 quart en verhit op middelhoog vuur.",
        "Laat de schenkels, zodra de boter gesmolten is en de olie glanst, met de platte kant naar beneden in de pan zakken. Passen ze niet zonder elkaar te raken, doe het dan in porties. Bruin ze en draai ze één keer met een tang, tot beide platte kanten goed gekarameliseerd zijn, ongeveer 5 minuten per kant.",
        "Beginnen de boter en de olie te verbranden, zet het vuur dan iets lager. Leg de schenkels op een grote schaal en zet ze opzij.",
        "De aromaten: giet het vet af en gooi het weg. Veeg de verbrande stukjes weg met een vochtig stuk keukenpapier en let erop dat je de goede gekarameliseerde stukjes laat zitten. Voeg de resterende 2 eetlepels boter toe en smelt ze op middelhoog vuur.",
        "Voeg, als de boter niet meer schuimt, de ui, de wortel, de selder en de venkel toe. Kruid met zout en peper, roer, en bak tot de groenten beginnen te verzachten maar niet kleuren, ongeveer 6 minuten. Roer de knoflook, de sinaasappelzeste, de marjolein en het laurierblad erdoor en stoof nog een minuut of twee.",
        "Het smoorvocht: voeg de wijn toe, zet het vuur hoog en breng aan de kook. Kook, af en toe roerend, tot de wijn ongeveer gehalveerd is, 5 minuten. Voeg de bouillon en de tomaten met hun sap toe en kook opnieuw in tot er in totaal ongeveer 1 kopje vocht over is, ongeveer 10 minuten.",
        "Het smoren: zet de schenkels in de pan met het blootliggende bot naar boven en giet er het vocht over dat is vrijgekomen terwijl ze stonden. Dek af met bakpapier en druk het aan zodat het het kalfsvlees bijna raakt en de randen een inch over de rand van de pan hangen.",
        "Sluit goed af met het deksel en schuif de pan in het onderste deel van de oven om zachtjes te smoren. Kijk na de eerste 15 minuten, en zet de oven 10 of 15 graden lager als het te hard borrelt.",
        "Smoor verder, draai de schenkels en lepel er na de eerste 40 minuten wat braadvocht over, tot het vlees helemaal zacht is en van het bot loslaat, ongeveer 2 uur.",
        "De gremolata: roer terwijl de schenkels smoren de knoflook, de peterselie en de citroenzeste door elkaar in een kommetje. Dek af met folie en zet koel weg, of in de koelkast als je keuken warm is.",
        "Afwerken: haal, als het kalfsvlees zacht is en van het bot valt, het deksel eraf en strooi de helft van de gremolata erover. Zet het nog 15 minuten onafgedekt terug in de oven om te karameliseren.",
        "Til de schenkels met een schuimspaan of lepel uit het smoorvocht en probeer ze heel te houden. Ze zijn heel zacht en vallen bijna uit elkaar, en het merg wiebelt in de botten, dus doe het traag.",
        "Breken ze toch, dan maakt het niet uit — de smaak is precies dezelfde. Leg ze zonder stapelen op een schaal en dek af met folie om ze warm te houden.",
        "De saus afwerken: zet de pan terug op het vuur en bekijk de saus. Ligt er een zichtbare laag vet bovenop, schep die er dan met een grote lepel af. Proef hoe geconcentreerd ze is.",
        "Smaakt ze zwak of vlak, breng ze dan op hoog vuur aan de kook en laat ze 5 tot 10 minuten inkoken. Proef opnieuw op zout en peper. Wil ze meer pit, roer er dan een theelepel of twee van de resterende gremolata door.",
        "Verdelen: zijn de schenkels van redelijke grootte, dien er dan één per persoon op. Zijn ze reusachtig, of de eetlust bescheiden, trek de grootste dan uit elkaar langs hun natuurlijke naden en dien kleinere porties op. Geef de mergpijpen aan wie ze het meest naar waarde schat.",
        "Opdienen: leg de schenkels op warme borden met de risotto, als je die erbij geeft. Strooi net voor je de borden naar tafel draagt de rest van de gremolata erover en lepel er royaal saus over — het hete vocht doet de knoflook en de citroen opengaan, en dat is wat mensen ruiken als het bord aankomt."
      ]
    },
    fr: {
      subtitle: "Deux heures dans un four doux, fini à la gremolata",
      description: "Des jarrets de veau braisés jusqu'à ce que la viande quitte l'os et que la moelle s'attendrisse dedans. La moitié de la gremolata entre pour le dernier quart d'heure, l'autre à table — la sauce brûlante la fait éclater.",
      instructions: [
        "Chauffe le four à 300 degrés.",
        "Fariner les jarrets : verse la farine dans un plat creux — un moule à tarte convient parfaitement. Assaisonne les jarrets de sel et de poivre sur toutes les faces. Un à un, roule-les dans la farine, puis secoue et tapote pour ôter l'excédent. Jette la farine restante.",
        "Colorer les jarrets : mets l'huile et 1 cuillère à soupe de beurre dans une cocotte large ou une braisière épaisse de 6 à 7 quarts et chauffe à feu moyen-vif.",
        "Quand le beurre a fondu et que l'huile miroite, dépose les jarrets côté plat dessous. S'ils ne tiennent pas sans se toucher, procède en plusieurs fois. Colore-les en les retournant une fois à la pince, jusqu'à ce que les deux faces plates soient bien caramélisées, environ 5 minutes par face.",
        "Si le beurre et l'huile commencent à brûler, baisse un peu le feu. Transfère les jarrets sur un grand plat et réserve.",
        "Les aromates : verse et jette la graisse. Essuie les parties brûlées avec un papier humide, en prenant soin de laisser les bons sucs caramélisés. Ajoute les 2 cuillères à soupe de beurre restantes et fais-les fondre à feu moyen.",
        "Quand le beurre a cessé de mousser, ajoute l'oignon, la carotte, le céleri et le fenouil. Assaisonne de sel et de poivre, remue, et cuis jusqu'à ce que les légumes commencent à fondre sans colorer, environ 6 minutes. Incorpore l'ail, le zeste d'orange, la marjolaine et le laurier et laisse compoter une minute ou deux.",
        "Le liquide de braisage : ajoute le vin, monte le feu à vif et porte à ébullition. Fais bouillir en remuant de temps en temps jusqu'à réduction de moitié environ, 5 minutes. Ajoute le bouillon et les tomates avec leur jus et fais bouillir de nouveau pour réduire le tout à environ 1 tasse, environ 10 minutes.",
        "Le braisage : place les jarrets dans la cocotte, l'os apparent vers le haut, et verse dessus les jus rendus pendant l'attente. Couvre de papier cuisson en l'appuyant pour qu'il touche presque le veau et que les bords dépassent d'un pouce.",
        "Couvre hermétiquement du couvercle et glisse dans la partie basse du four pour braiser à petit frémissement. Vérifie après les 15 premières minutes, et si ça frémit trop fort, baisse le four de 10 ou 15 degrés.",
        "Poursuis le braisage, en retournant les jarrets et en les arrosant de jus après les 40 premières minutes, jusqu'à ce que la viande soit parfaitement tendre et se détache de l'os, environ 2 heures.",
        "La gremolata : pendant que les jarrets braisent, mélange l'ail, le persil et le zeste de citron dans un petit bol. Couvre de film et garde au frais, ou au réfrigérateur si ta cuisine est chaude.",
        "La finition : quand le veau se défait à la fourchette et quitte l'os, retire le couvercle et parsème la moitié de la gremolata. Remets au four à découvert 15 minutes de plus pour caraméliser.",
        "À l'écumoire ou à la spatule ajourée, sors les jarrets du liquide en faisant de ton mieux pour les garder entiers. Ils seront très tendres et prêts à se défaire, et la moelle tremblera dans les os, alors vas-y doucement.",
        "S'ils se cassent, aucune importance — le goût est exactement le même. Dispose-les sur un plat sans les empiler et couvre d'aluminium pour les garder chauds.",
        "Finir la sauce : remets la cocotte sur le feu et regarde la sauce. S'il y a une couche de gras visible en surface, dégraisse à la grande cuillère. Goûte-en la concentration.",
        "Si elle paraît faible ou plate, porte-la à ébullition à feu vif et réduis 5 à 10 minutes pour l'intensifier. Goûte de nouveau le sel et le poivre. Si elle manque de nerf, incorpore une cuillère à café ou deux de la gremolata restante.",
        "Le partage : si les jarrets sont de taille raisonnable, sers-en un par personne. S'ils sont énormes, ou les appétits modestes, sépare les plus gros à leurs jointures naturelles et sers de plus petites portions. Donne les os à moelle à qui les apprécie le plus.",
        "Le service : dispose les jarrets sur des assiettes chaudes avec le risotto, si tu en sers. Juste avant de porter à table, parsème le reste de la gremolata et nappe généreusement de sauce — le liquide brûlant libère l'ail et le citron, et c'est ce que les gens sentent quand l'assiette arrive."
      ]
    }
  },

  "mealdb-52807": {
    en: {
      subtitle: "Roasted over the flame until the skin blisters black",
      description: "The aubergine goes straight onto the burner until the skin chars and the flesh collapses, and that smoke is the dish. Oven-roasting works, but you lose the very thing you came for.",
      instructions: [
        "Rinse the baingan — the aubergine — in water. Pat it dry with a kitchen towel and rub oil all over it.",
        "Set it over an open flame to roast. You can grill it or roast it in the oven instead, but then you won't get",
        "the smoky flavour that is the whole point. Turn it every 2 to 3 minutes over the flame so it cooks evenly",
        "all round. You can also push a few garlic cloves into the aubergine before roasting it.",
        "Roast it until it is completely cooked and tender. Check with a knife — the blade should slide",
        "in without any resistance. Take it off and drop it into a bowl of water until it cools down.",
        "You can also do the dhungar technique, infusing charcoal smoke into the baingan. This step is optional.",
        "Use natural charcoal. Heat a small piece over the flame until it is smoking hot and glowing red.",
        "Cut small slits in the baingan with a knife. Set the red hot charcoal on the same plate as the roasted",
        "aubergine. Add a few drops of oil onto the charcoal, and it will begin to smoke.",
        "As soon as the smoke starts, cover the whole plate tightly with a large bowl. Let the",
        "smoke infuse for 1 to 2 minutes. The longer you leave it, the smokier the bharta",
        "gets — a minute is plenty for most people. You can also do the dhungar once the bharta is",
        "cooked, the same way it is done for dal tadka.",
        "Peel the skin off the roasted and smoked aubergine.",
        "Chop the cooked flesh finely, or mash it if you prefer.",
        "Heat oil in a kadai or pan, then add the finely chopped onions and garlic.",
        "Sauté the onions until translucent. Don't let them brown.",
        "Add the chopped green chillies and sauté for a minute.",
        "Add the chopped tomatoes and mix well.",
        "Bhuno — keep sautéing — until the oil starts to separate from the mixture.",
        "Now add the red chilli powder. Stir and mix well.",
        "Add the chopped cooked baingan.",
        "Stir and mix the aubergine thoroughly through the onion-tomato masala.",
        "Season with salt. Stir and sauté another 4 to 5 minutes.",
        "Finally stir the coriander leaves through the bharta, or scatter them over. Serve it with",
        "phulkas, rotis or chapatis. It is good with bread too, toasted or grilled, and with plain or jeera rice."
      ]
    },
    nl: {
      subtitle: "Boven de vlam geroosterd tot de schil zwart blaast",
      description: "De aubergine gaat recht op de brander tot de schil verkoolt en het vruchtvlees inzakt, en die rook ís het gerecht. In de oven kan ook, maar dan mis je net waarvoor je kwam.",
      instructions: [
        "Spoel de baingan — de aubergine — af met water. Dep hem droog met een keukendoek en wrijf hem helemaal in met olie.",
        "Leg hem boven een open vlam om te roosteren. Je kan hem ook grillen of in de oven roosteren, maar dan krijg je",
        "de rokerige smaak niet die de hele bedoeling is. Draai hem elke 2 tot 3 minuten boven de vlam zodat hij gelijkmatig",
        "gaart. Je kan ook een paar teentjes knoflook in de aubergine duwen voor je hem roostert.",
        "Rooster hem tot hij helemaal gaar en zacht is. Controleer met een mes — het lemmet hoort er",
        "zonder weerstand in te glijden. Haal hem eraf en laat hem in een kom water zakken tot hij afgekoeld is.",
        "Je kan ook de dhungar-techniek doen, waarbij je houtskoolrook in de baingan trekt. Deze stap is optioneel.",
        "Gebruik natuurlijke houtskool. Verhit een klein stukje boven de vlam tot het rokend heet en roodgloeiend is.",
        "Snijd met een mes kleine gleufjes in de baingan. Zet de roodgloeiende houtskool op hetzelfde bord als de geroosterde",
        "aubergine. Doe een paar druppels olie op de houtskool, en die begint te roken.",
        "Dek zodra de rook opkomt het hele bord strak af met een grote kom. Laat de",
        "rook 1 tot 2 minuten intrekken. Hoe langer je het laat staan, hoe rokeriger de bharta",
        "wordt — voor de meeste mensen is een minuut ruim genoeg. Je kan de dhungar ook doen als de bharta",
        "al klaar is, net zoals bij dal tadka.",
        "Trek de schil van de geroosterde en gerookte aubergine.",
        "Hak het gare vruchtvlees fijn, of prak het als je dat liever hebt.",
        "Verhit olie in een kadai of pan en voeg dan de fijngesneden ui en knoflook toe.",
        "Fruit de ui tot ze glazig is. Laat ze niet kleuren.",
        "Voeg de gesneden groene pepers toe en bak een minuut.",
        "Voeg de gesneden tomaten toe en meng goed.",
        "Bhuno — blijf bakken — tot de olie zich van het mengsel begint te scheiden.",
        "Voeg nu het rodepeperpoeder toe. Roer en meng goed.",
        "Voeg de gesneden gare baingan toe.",
        "Roer en meng de aubergine grondig door de masala van ui en tomaat.",
        "Breng op smaak met zout. Roer en bak nog 4 tot 5 minuten.",
        "Roer tot slot de korianderblaadjes door de bharta, of strooi ze erover. Dien hem op met",
        "phulka's, roti's of chapati's. Hij is ook lekker met brood, getoost of gegrild, en met gewone of jeera-rijst."
      ]
    },
    fr: {
      subtitle: "Rôtie sur la flamme jusqu'à ce que la peau noircisse",
      description: "L'aubergine va directement sur le brûleur jusqu'à ce que la peau charbonne et que la chair s'effondre, et cette fumée est le plat même. Au four ça marche, mais tu perds précisément ce que tu venais chercher.",
      instructions: [
        "Rince la baingan — l'aubergine — à l'eau. Sèche-la avec un torchon et enduis-la d'huile partout.",
        "Pose-la sur une flamme nue pour la rôtir. Tu peux aussi la griller ou la rôtir au four, mais alors tu n'auras pas",
        "ce goût fumé qui est tout l'intérêt. Tourne-la toutes les 2 à 3 minutes sur la flamme pour qu'elle cuise",
        "régulièrement. Tu peux aussi enfoncer quelques gousses d'ail dans l'aubergine avant de la rôtir.",
        "Rôtis-la jusqu'à ce qu'elle soit parfaitement cuite et tendre. Vérifie au couteau — la lame doit glisser",
        "sans aucune résistance. Retire-la et plonge-la dans un bol d'eau jusqu'à refroidissement.",
        "Tu peux aussi pratiquer la technique du dhungar, qui infuse une fumée de charbon dans la baingan. Cette étape est facultative.",
        "Utilise du charbon naturel. Chauffe un petit morceau sur la flamme jusqu'à ce qu'il soit brûlant et rouge.",
        "Fais de petites entailles dans la baingan au couteau. Pose le charbon rougi sur la même assiette que l'aubergine",
        "rôtie. Verse quelques gouttes d'huile sur le charbon, et il se mettra à fumer.",
        "Dès que la fumée monte, couvre toute l'assiette hermétiquement d'un grand bol. Laisse la",
        "fumée infuser 1 à 2 minutes. Plus tu laisses, plus la bharta sera",
        "fumée — une minute suffit largement à la plupart des gens. Tu peux aussi faire le dhungar une fois la bharta",
        "cuite, exactement comme pour un dal tadka.",
        "Retire la peau de l'aubergine rôtie et fumée.",
        "Hache finement la chair cuite, ou écrase-la si tu préfères.",
        "Chauffe l'huile dans un kadai ou une poêle, puis ajoute l'oignon et l'ail finement hachés.",
        "Fais revenir l'oignon jusqu'à ce qu'il soit translucide. Ne le laisse pas colorer.",
        "Ajoute les piments verts hachés et fais revenir une minute.",
        "Ajoute les tomates concassées et mélange bien.",
        "Bhuno — continue de faire revenir — jusqu'à ce que l'huile commence à se séparer du mélange.",
        "Ajoute maintenant la poudre de piment rouge. Remue et mélange bien.",
        "Ajoute la baingan cuite et hachée.",
        "Remue et mélange soigneusement l'aubergine au masala d'oignon et de tomate.",
        "Assaisonne de sel. Remue et fais revenir encore 4 à 5 minutes.",
        "Incorpore enfin les feuilles de coriandre à la bharta, ou parsème-les dessus. Sers-la avec des",
        "phulkas, des rotis ou des chapatis. Elle est bonne aussi avec du pain, grillé, et avec du riz nature ou au cumin."
      ]
    }
  },

  "mealdb-52805": {
    en: {
      subtitle: "Rice at 80 per cent, layered over the lamb and finished sealed",
      description: "The rice is boiled only until it is four-fifths done — the last fifth happens sealed over the lamb, in its steam. Fried onions, saffron milk and ghee go between the layers.",
      instructions: [
        "Grind the cashew, poppy seeds and cumin seeds into a smooth paste, using as little water as you can. Set it aside.",
        "Deep fry the sliced onions once the oil is hot, without crowding it. When they turn light brown, lift them out and drain them on paper towel — they crisp up as they drain, not in the pan. Fry the cashews until golden brown too. Set both aside.",
        "Wash the rice and soak it in water for twenty minutes.",
        "Meanwhile, take a big wide pan, heat oil over medium heat, add the sliced onions, then the ground paste, then the green chillies, ginger garlic paste and garlic, and fry for a minute.",
        "Then add the tomatoes and sauté until they are cooked but not mushy.",
        "Add the red chilli powder, biryani powder, mint and coriander leaves and sauté well.",
        "Add the yogurt and mix well. Move the pan off the heat as you add it — that is what stops the yogurt splitting.",
        "Back on the stove, add the washed lamb, salt and ½ cup water and mix well. Cook covered on medium-low heat for 1 hour, or 6 whistles in a pressure cooker. If any liquid is left, cook it off uncovered.",
        "Take another big pan and boil three times the volume of water to rice. When it is at a rolling boil, add the rice, salt and jeera and stir. After 7 minutes exactly, or when the rice is 80% done, switch it off and drain it.",
        "Now the layering. Pat the lamb down level. Spread the drained hot rice over it. Scatter over the fried onions, ghee, mint, coriander leaves and the saffron dissolved in milk.",
        "Cover the dish and bake at 350f for 15 minutes, or until cooked but not mushy. On the stove instead: 12 minutes on medium and 5 minutes on the lowest heat, then switch off. Mix and serve hot. A few notes.",
        "If you are using the oven, use a big oven-safe pan and cover it tightly for that final step.",
        "You can skip the biryani masala if you don't have it and use garam masala instead — 1 tsp, with 3 tsp red chilli powder rather than 1 tsp.",
        "If it comes out too hot, squeeze in some lemon. It takes the heat down and lifts the other flavours at the same time."
      ]
    },
    nl: {
      subtitle: "Rijst op 80 procent, over het lam gelaagd en afgedekt afgewerkt",
      description: "De rijst kookt maar tot ze voor vier vijfde gaar is — het laatste vijfde gebeurt afgedekt boven het lam, in zijn stoom. Gebakken ui, saffraanmelk en ghee gaan tussen de lagen.",
      instructions: [
        "Maal de cashewnoten, de maanzaad en de komijnzaadjes tot een gladde pasta, met zo weinig water als je kan. Zet opzij.",
        "Frituur de gesneden uien zodra de olie heet is, zonder de pan te vol te doen. Haal ze eruit als ze lichtbruin kleuren en laat ze uitlekken op keukenpapier — ze worden krokant tijdens het uitlekken, niet in de pan. Bak ook de cashewnoten goudbruin. Zet beide opzij.",
        "Was de rijst en week ze twintig minuten in water.",
        "Neem ondertussen een grote brede pan, verhit olie op middelhoog vuur, voeg de gesneden uien toe, dan de gemalen pasta, dan de groene pepers, de gember-knoflookpasta en de knoflook, en bak een minuut.",
        "Voeg dan de tomaten toe en bak ze goed tot ze gaar zijn maar niet papperig.",
        "Voeg het rodepeperpoeder, het biryanipoeder, de munt en de korianderblaadjes toe en bak goed door.",
        "Voeg de yoghurt toe en meng goed. Haal de pan van het vuur terwijl je hem toevoegt — dat is net wat belet dat de yoghurt schift.",
        "Voeg terug op het vuur het gewassen lamsvlees, het zout en ½ kopje water toe en meng goed. Gaar afgedekt 1 uur op middellaag vuur, of 6 fluitjes in een snelkookpan. Blijft er vocht over, kook het dan open weg.",
        "Neem nog een grote pan en breng drie keer het volume van de rijst aan water aan de kook. Voeg als het hard kookt de rijst, het zout en de jeera toe en roer. Zet na exact 7 minuten uit, of als de rijst voor 80% gaar is, en giet ze af.",
        "Nu het lagen. Druk het lam vlak. Verdeel de afgegoten hete rijst erover. Strooi er de gebakken uien, de ghee, de munt, de korianderblaadjes en de in melk opgeloste saffraan over.",
        "Dek de schaal af en bak 15 minuten op 350f, of tot ze gaar is maar niet papperig. Op het vuur in plaats daarvan: 12 minuten op middelhoog en 5 minuten op het laagste vuur, en dan uitzetten. Meng en dien heet op. Nog een paar bemerkingen.",
        "Gebruik je de oven, neem dan een grote ovenvaste pan en dek ze goed af voor die laatste stap.",
        "Je mag de biryanimasala overslaan als je die niet hebt en in de plaats garam masala nemen — 1 tl, met 3 tl rodepeperpoeder in plaats van 1 tl.",
        "Komt hij te pittig uit, knijp er dan wat citroen over. Dat haalt de scherpte eraf en tilt tegelijk de andere smaken op."
      ]
    },
    fr: {
      subtitle: "Le riz à 80 pour cent, superposé sur l'agneau et fini à couvert",
      description: "Le riz ne cuit que jusqu'aux quatre cinquièmes — le dernier cinquième se fait à couvert sur l'agneau, dans sa vapeur. Oignons frits, lait safrané et ghee vont entre les couches.",
      instructions: [
        "Mouds les noix de cajou, les graines de pavot et le cumin en une pâte lisse, avec le moins d'eau possible. Réserve.",
        "Fais frire les oignons émincés une fois l'huile chaude, sans surcharger. Quand ils brunissent légèrement, sors-les et égoutte-les sur du papier absorbant — ils croustillent en égouttant, pas dans l'huile. Fais aussi dorer les noix de cajou. Réserve les deux.",
        "Lave le riz et fais-le tremper vingt minutes dans l'eau.",
        "Pendant ce temps, prends une grande poêle large, chauffe l'huile à feu moyen, ajoute les oignons émincés, puis la pâte moulue, puis les piments verts, la pâte gingembre-ail et l'ail, et fais revenir une minute.",
        "Ajoute ensuite les tomates et fais-les revenir jusqu'à ce qu'elles soient cuites sans être en bouillie.",
        "Ajoute la poudre de piment rouge, le mélange biryani, la menthe et la coriandre et fais bien revenir.",
        "Ajoute le yaourt et mélange bien. Écarte la poêle du feu au moment de l'ajouter — c'est ce qui empêche le yaourt de trancher.",
        "De retour sur le feu, ajoute l'agneau lavé, le sel et ½ tasse d'eau et mélange bien. Cuis à couvert à feu moyen-doux pendant 1 heure, ou 6 sifflements à l'autocuiseur. S'il reste du liquide, fais-le évaporer à découvert.",
        "Prends une autre grande casserole et porte à ébullition trois fois le volume d'eau par rapport au riz. À gros bouillons, ajoute le riz, le sel et le cumin et remue. Après 7 minutes exactement, ou quand le riz est cuit à 80%, coupe le feu et égoutte.",
        "Le montage maintenant. Tasse l'agneau à plat. Étale le riz chaud égoutté dessus. Parsème les oignons frits, le ghee, la menthe, la coriandre et le safran dissous dans le lait.",
        "Couvre le plat et cuis à 350f pendant 15 minutes, ou jusqu'à ce que ce soit cuit sans être pâteux. Sur le feu à la place : 12 minutes à feu moyen et 5 minutes au plus doux, puis coupe. Mélange et sers chaud. Quelques remarques.",
        "Si tu utilises le four, prends une grande cocotte allant au four et couvre-la hermétiquement pour cette dernière étape.",
        "Tu peux te passer du mélange biryani si tu n'en as pas et prendre du garam masala à la place — 1 c. à café, avec 3 c. à café de piment rouge plutôt que 1 c. à café.",
        "S'il ressort trop relevé, presse un peu de citron. Cela calme le feu et relève les autres saveurs en même temps."
      ]
    }
  }
};
